### ISSUE TITLE
关于EasySQL的问题

### ISSUE THREAD

**Issue by Natsukiw** [CarmJos/CarmJos#7]
我的世界服务器.
我尝试输入指令测试EasySQL进行数据库查询(同步查询)
刚开始的前几次查询是没问题的,查询几次之后就出现超时报错 (使用异步查询(executeAsync)则没有这个问题)
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.

当我在SQLQuery查询完毕后执行close()操作,这个问题则解决了,但是教程并没有提示需要close()

我自学的Java,不清楚这样close()之后会不会有问题,会不会出现频繁的创建关闭操作从而消耗过多资源?

然后我应不应该每次查询之后都执行close()操作?
如果需要执行close()操作,那么同步和异步是否都需要close()?

**Comment by Natsukiw** [comment]
```java
try
{
    SQLQuery execute = SQLSystem.manager.createQuery().inTable(SQL_TABLE).selectColumns("id", "data").build().execute();
    ResultSet set = execute.getResultSet();
    while (set.next())
    {
        String id = set.getString("id");
        String data = set.getString("data");
        System.out.println("DEBUG: " + id);
    }
    execute.close();
} catch (SQLException e)
{
    e.printStackTrace();
}
```
相关代码

**Comment by CarmJos** [comment]
您好，很高兴您能提问关于 EasySQL 的问题。

首先，`SQLQuery` 继承了 `AutoCloseable`，即应当使用 `try-with-resources` 方式进行 SQLQuery的操作。这是JDBC操作的基础操作，此点我相信您的编辑器也会发出相关警告，如图所示。

![SQLQuery未使用try-with-resources](https://user-images.githubusercontent.com/36306882/236837165-03591d34-2ff6-4419-85a5-0d959e9110ae.png)

使用  `try-with-resources` 方式后，在try代码块结束或出现错误中断后，将自动关闭SQLQuery，无需再次手动`close()`。

以上内容在 [Bob的EasySQL之旅(HikariCP)](https://github.com/CarmJos/EasySQL/blob/master/.documentation/USAGE-HIKARI.md) 教程文档中也有[提到(#同步请求)](https://github.com/CarmJos/EasySQL/blob/master/.documentation/USAGE-HIKARI.md#%E5%90%8C%E6%AD%A5%E8%AF%B7%E6%B1%82)。

--- 

同时，EasySQL提供了更加优雅的 lambda 操作方式(包括同步和异步方式)。使用此方式时，也无需手动关闭查询。此方式在上述的教程文档中也有提到。若以您给出的实例来写，它大概看起来是这样的：

```java
        Map<String, String> result = sql.createQuery().inTable(TABLE_NAME).build().execute(
                (query) -> {
                    ResultSet rs = query.getResultSet();
                    Map<String, String> map = new HashMap<>();
                    while (rs.next()) {
                        String id = rs.getString("id");
                        String data = rs.getString("data");
                        map.put(id, data);

                        System.out.println("DEBUG: " + id + " -> " + data);
                    }
                    return map;
                },
                (ex, action) -> ex.printStackTrace() // 可选，默认是打印异常。
        );
```

**Comment by CarmJos** [comment]
如有任何其他问题，您可以继续提问，我将尽力为您解答哦~

**Comment by Natsukiw** [comment]
> 如有任何其他问题，您可以继续提问，我将尽力为您解答哦~

好的,很详细的解疑,我明白了,谢谢你!

**Comment by CarmJos** [comment]
嗯呐，非常开心可以帮到您。您可以关注我和EasySQL项目，后续将会有更多的更新。
